version: "3"
services:
  blog-api:
    build: .
    container_name: blog-api
    depends_on:
    - blog-postgres
    env_file: .env
    links:
    - blog-postgres
    ports:
    - "3000:80"
    volumes:
    - ./:/usr/src/rust-blog-api
  blog-postgres:
    container_name: blog-postgres
    env_file: .env
    image: postgres
    ports:
    - "5433:5432"
