[package]
authors = ["Zachary Golba <zachary.golba@postlight.com>"]
name = "blog-fmt"
version = "0.1.0"

[dependencies]
Inflector = "0.10.1"
chrono = "0.4.0"
rocket = "0.3.0"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.2"
